version: "3"

services:
  postgres:
    image: postgres
    tty: true
    container_name: effective_mobile_test_task
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
